### ISSUE TITLE
Changing the phone from portrait to landscape orientation 

### ISSUE THREAD

**Issue by Nikonok80** [aj3423/SpamBlocker#114]
Hello! Thank you for your work, great app. There was a problem creating a rule for numbers. I opened the rule creation window and turned the phone to landscape orientation. 

android version: 34
app version: 1.20
K1.h: lateinit property initFilter has not been initialized
	at i2.r.G(Unknown Source:1341)
	at e0.U.f(Unknown Source:298)
	at e0.U.k(Unknown Source:146)
	at e0.N.N(Unknown Source:61)
	at e0.N.t(Unknown Source:35)
	at h.i.D(Unknown Source:33)
	at h.i.onStart(Unknown Source:0)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1582)
	at android.app.Activity.performStart(Activity.java:9008)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4198)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by aj3423** [comment]
Ah I see, I'm rewriting the UI, this bug will be fixed then.
