### ISSUE TITLE
Just after says me to delete the SMS app

### ISSUE THREAD

**Issue by acmartinsalmeida** [aj3423/SpamBlocker#122]
android version: 34
app version: 1.20
java.lang.RuntimeException: Unable to resume activity {spam.blocker/spam.blocker.ui.main.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5270)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5303)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:282)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:150)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Object.equals(java.lang.Object)' on a null object reference
	at android.permission.PermissionManager.checkPackageNamePermissionUncached(PermissionManager.java:1925)
	at android.permission.PermissionManager.-$$Nest$smcheckPackageNamePermissionUncached(Unknown Source:0)
	at android.permission.PermissionManager$2.recompute(PermissionManager.java:1943)
	at android.permission.PermissionManager$2.recompute(PermissionManager.java:1940)
	at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:999)
	at android.permission.PermissionManager.checkPackageNamePermission(PermissionManager.java:1960)
	at android.app.ApplicationPackageManager.checkPermission(ApplicationPackageManager.java:847)
	at Z0.e.g(Unknown Source:22)
	at spam.blocker.ui.setting.SettingFragment.C(Unknown Source:119)
	at e0.U.n(Unknown Source:148)
	at e0.U.k(Unknown Source:58)
	at e0.N.N(Unknown Source:61)
	at e0.N.t(Unknown Source:35)
	at e0.U.n(Unknown Source:183)
	at e0.U.k(Unknown Source:58)
	at e0.N.N(Unknown Source:61)
	at e0.N.t(Unknown Source:35)
	at h.i.C(Unknown Source:28)
	at h.i.onPostResume(Unknown Source:0)
	at android.app.Activity.performResume(Activity.java:9198)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5260)
	... 16 more

**Comment by aj3423** [comment]
It crashed at this line:
https://github.com/aj3423/SpamBlocker/blob/a5af7d8711503081eef710c074f26d66606da484/app/src/main/java/spam/blocker/util/Util.kt#L268

It was trying to check if your default SMS app granted notification permission.
But somehow it failed to get the package name of the default app, do you have any app set as the default SMS app?

Just fixed this in the latest tag:
https://github.com/aj3423/SpamBlocker/releases/tag/latest

**Comment by acmartinsalmeida** [comment]
You're right.
At the time of installing, SMS app was not defined.
Thanks for this
