### ISSUE TITLE
Error in the application when testing the blocking rules 

### ISSUE THREAD

**Issue by Slawa79** [aj3423/SpamBlocker#125]
There was an error in the application, it was suggested to send the copied text here, here I am sending it.
android version: 33
app version: 1.20
java.lang.RuntimeException: Error receiving broadcast Intent { act=on_new_call flg=0x80010 (has extras) } in s2.h@d39d371
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1914)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8370)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.NullPointerException
	at s2.h.onReceive(Unknown Source:45)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1878)
	... 9 more
![Screenshot_2024-09-10-11-58-43-22_da2992a9ae338eaa76b5ad04eb856598.jpg](https://github.com/user-attachments/assets/57418e01-0fca-4fc7-8b38-0779236a3ccc)

![Screenshot_2024-09-10-11-58-29-70_da2992a9ae338eaa76b5ad04eb856598.jpg](https://github.com/user-attachments/assets/5bc38839-173f-46ec-926e-20a19d3101bc)

![Screenshot_2024-09-10-11-58-49-25_da2992a9ae338eaa76b5ad04eb856598.jpg](https://github.com/user-attachments/assets/8fe903f4-942d-4f96-a41b-2ab9bfeb01f4)

**Comment by aj3423** [comment]
Thanks for reporting.

This problem exists in the first "latest" release, it has been fixed since two days ago. Upgrading to newer version won't solve this, could you please try:
1. backup you current settings
2. uninstall this app
3. install the latest tag again.
4. restore your settings

It should fix this problem.
