### ISSUE TITLE
导入200m数据库出错，超容量了？

### ISSUE THREAD

**Issue by rachilee** [aj3423/SpamBlocker#168]
android version: 30
app version: 3.3
java.lang.OutOfMemoryError: Failed to allocate a 363810184 byte allocation with 25165824 free bytes and 77MB until OOM, target footprint 211987400, growth limit 268435456
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:125)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:249)
	at W2.n0.z(Unknown Source:53)
	at L2.i0.i(Unknown Source:69)
	at L2.b.a(Unknown Source:37)
	at R2.e.p(Unknown Source:7)
	at T1.a.t(Unknown Source:7)
	at l2.D.run(Unknown Source:112)
	at A1.a.run(Unknown Source:275)
	at s2.i.run(Unknown Source:2)
	at s2.a.run(Unknown Source:91)
	Suppressed: q2.g: [s0.y0@4897b2c, H.h@21909f5, m0{Cancelling}@e30138a, Y@89c19bd]

**Comment by rachilee** [comment]
抱歉，可能是刚开始没明白使用方法。
我用正则提取号码导入没问题了，感谢开发这么强大而又简洁的软件。
