### ISSUE TITLE
导入数据库时崩溃了

### ISSUE THREAD

**Issue by Miku196** [aj3423/SpamBlocker#194]
### SpamBlocker version

3.4

### Android version

10

### The issue

日志：
android version: 33
app version: 3.4
java.lang.OutOfMemoryError: Failed to allocate a 183214624 byte allocation with 100663296 free bytes and 160MB until OOM, target footprint 200975360, growth limit 268435456
	at java.lang.StringFactory.newStringFromUtf8Bytes(Native Method)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:80)
	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:101)
	at S2.b.j(Unknown Source:39)
	at L2.g.k(Unknown Source:258)
	at G2.f.a(Unknown Source:10)
	at b.j.a(Unknown Source:48)
	at b.l.onActivityResult(Unknown Source:2)
	at android.app.Activity.dispatchActivityResult(Activity.java:8665)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5332)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5378)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by aj3423** [comment]
Can you show me the first 3 rows of the .csv file? I need the header information. 
And how many rows are there?

**Comment by aj3423** [comment]
Without further information I can only guess that you mischose a wrong file, maybe an mp4 file, because usually the backup file won't be that huge.

I fixed it by limiting the mime type of the file chooser, now you can only select .gz files: https://github.com/aj3423/SpamBlocker/actions/runs/11990614648

I'm closing  this, feel free to re-open.
