### ISSUE TITLE
app crashes

### ISSUE THREAD

**Issue by nullll1** [aj3423/SpamBlocker#216]
### SpamBlocker version

3.5

### Android version

15 (BP11.241025.006)

### The issue

app crashes after open
android version: 35
app version: 3.5
android.database.sqlite.SQLiteException: no such table: api_query (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM api_query  ORDER BY description
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.-$$Nest$smnativePrepareStatement(Unknown Source:0)
	at android.database.sqlite.SQLiteConnection$PreparedStatementCache.createStatement(SQLiteConnection.java:1571)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatementLI(SQLiteConnection.java:1108)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1136)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:696)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:625)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1851)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1783)
	at A2.G.h(Unknown Source:52)
	at S2.m.a(Unknown Source:12)
	at R2.t.g(Unknown Source:7)
	at T1.a.u(Unknown Source:7)
	at l2.D.run(Unknown Source:112)
	at r0.W.z(Unknown Source:23)
	at r0.V.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
	Suppressed: q2.g: [r0.t0@5570fea, G.g@5e742db, A{Cancelling}@a386178, W@2844051]

**Comment by aj3423** [comment]
Thank you for the quick feedback. It's  the latest release, right?

**Comment by aj3423** [comment]
> Q:Does the info that I provided include sensitive stuff?

No it doesn't contain anything sensitive, it's just some database function names, I'm looking into it.

**Comment by aj3423** [comment]
pls try this action: https://github.com/aj3423/SpamBlocker/actions/runs/12209726022

**Comment by aj3423** [comment]
Ok, sorry for this trouble, and thanks.
