### ISSUE TITLE
Crash if regex priority is empty

### ISSUE THREAD

**Issue by AustralEpitech** [aj3423/SpamBlocker#81]
To reproduce:
- Click on `Add` in the `Number rules` section, in `Regex Settings`
- Empty the field `Priority`
- Click `Save`

I guess the bug is pretty obvious, but here is the crash log:
```
java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:800)
	at java.lang.Integer.parseInt(Integer.java:908)
	at spam.blocker.ui.setting.PopupEditRuleFragment.onViewCreated$lambda$8(PopupEditRuleFragment.kt:245)
	at spam.blocker.ui.setting.PopupEditRuleFragment.$r8$lambda$cp3ZFpdfJ4pGmVCq1Yvlg6NMy0U(Unknown Source:0)
	at spam.blocker.ui.setting.PopupEditRuleFragment$$ExternalSyntheticLambda7.onClick(D8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7931)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
	at android.view.View.performClickInternal(View.java:7908)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30989)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by aj3423** [comment]
fixed in the action build: https://github.com/aj3423/SpamBlocker/actions/runs/9573976890
When it's empty, there will be an error prompt and cannot be saved.
![image](https://github.com/aj3423/SpamBlocker/assets/4710875/b9d6b24e-12cf-416a-8d5e-9f2fb008ed88)
