### ISSUE TITLE
Unable to start activity Excpetion

### ISSUE THREAD

**Issue by LoHub** [aj3423/SpamBlocker#99]
I encountered this error:

```
version: 1.17
java.lang.RuntimeException: Unable to start activity ComponentInfo{spam.blocker/spam.blocker.ui.main.MainActivity}: K1.h: Unable to instantiate fragment i2.t: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4004)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4184)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6268)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6159)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:80)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: K1.h: Unable to instantiate fragment i2.t: could not find Fragment constructor
	at e0.H.a(Unknown Source:58)
	at e0.T.a(Unknown Source:2)
	at e0.U.<init>(SourceFile:13)
	at e0.N.U(Unknown Source:252)
	at e0.N.b(Unknown Source:217)
	at b.f.a(Unknown Source:18)
	at b.n.onCreate(Unknown Source:30)
	at h.i.onCreate(Unknown Source:0)
	at spam.blocker.ui.main.MainActivity.onCreate(Unknown Source:6)
	at android.app.Activity.performCreate(Activity.java:9013)
	at android.app.Activity.performCreate(Activity.java:8991)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3986)
	... 18 more
Caused by: java.lang.NoSuchMethodException: i2.t.<init> []
	at java.lang.Class.getConstructor0(Class.java:3395)
	at java.lang.Class.getConstructor(Class.java:2487)
	at e0.H.a(Unknown Source:19)
	... 30 more
```

Unfortunately, I am not able to reproduce it.

**Comment by aj3423** [comment]
Thanks for reporting.
Seems Android is not happy with custom Fragment constructors, I modified them to the default constructor, fixed in the latest tag.
